# VS code support
windowrule = match:class code, match:title ^(Открыть папку|Открыть файл|Открыть|Сохранить|Выбрать|Open|Save|Select).*, float on, center on

# Screenshots support
# noanim isn't necessary but animations with these rules might look bad. use at your own discretion.
# set this to your leftmost monitor id, otherwise you have to move your cursor to the leftmost monitor
# before executing flameshot
windowrule = match:class ^(flameshot)$, no_anim on, float on, move 0 0, pin on, no_initial_focus on, monitor 1