# -----------------------------------------------------
# Window rules
# -----------------------------------------------------

# Pavucontrol floating
windowrule = match:class (.*org.pulseaudio.pavucontrol.*), float on, size 700 600, center on, pin on

# Waypaper
windowrule = match:class (.*waypaper.*), float on, size 900 700, center on, pin on

# SwayNC
layerrule = match:namespace swaync-control-center, blur on, ignore_alpha 0.5
layerrule = match:namespace swaync-notification-window, blur on, ignore_alpha 0.5

# Blueman Manager
windowrule = match:class (blueman-manager), float on, size 800 600, center on

# System Mission Center
windowrule = match:class (io.missioncenter.MissionCenter), float on, pin on, center on, size 900 600

# System Mission Center Preference Window
windowrule = match:class (missioncenter), match:title ^(Preferences)$, float on, pin on, center on

# Hyprland Share Picker
windowrule = match:class (hyprland-share-picker), float on, pin on, center on, size 600 400

# General floating
windowrule = match:class (dotfiles-floating), float on, size 1000 700, center on

# Float and center file pickers
windowrule = match:class xdg-desktop-portal-gtk, match:title ^(Open.*Files?|Save.*Files?|All Files|Save|Открыть|Сохранить|Выбрать), float on, center on

# Browser Picture in Picture
windowrule = match:title ^(Picture-in-Picture)$, float on, pin on, move 69.5% 4%

# idleinhibit
windowrule = match:class ([window]), idle_inhibit fullscreen # Available modes: none, always, focus, fullscreen

#xwayland related rules
# when moving objects in resolve a large border is produced
# This rule prevents that and serves as a template for any problematic xwayland apps
windowrule = match:class ^(\bresolve\b)$, match:xwayland true, no_blur on
# This is a general rule for xwayland apps but can have other consequences
# for one user it impacted EMACs so it's disabled by default
# It's here as a reference or for quick triage of xwayland ap
#windowrule = match:xwayland true, no_blur on